services:
  api:
    build:
      dockerfile: Dockerfile.api
    container_name: pw-api
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8393/docs"]
      interval: 3s
      timeout: 10s
      retries: 5
    restart: always
    ports:
    - "8393:8393"
    volumes:
      - ./api:/api

  web:
    build:
      dockerfile: Dockerfile.web
    container_name: pw-web
    depends_on:
      api:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: always
    ports:
    - "80:80"
    volumes:
      - ./dist:/usr/share/nginx/html

  db:
    image: postgres:16.2
    container_name: pw-postgres
    restart: always
    environment:
      POSTGRES_DB: pitchdb
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 3s
      timeout: 10s
      retries: 5
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume:
