FROM python:3.11

ENV PYTHONPATH "${PYTHONPATH}:/api/src"

WORKDIR /api

COPY setup/requirements.txt /api/requirements.txt
COPY api /api/

RUN pip install --no-cache-dir --upgrade -r requirements.txt
