FROM python:3.11
ENV PYTHONPATH "${PYTHONPATH}:/api/src"

WORKDIR /api

COPY requirements.txt /api/requirements.txt
COPY alembic.ini /api/alembic.ini
COPY api /api/

RUN pip install --no-cache-dir --upgrade -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8393"]
