name: pytest Unit Tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pytest:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r setup/requirements.txt -r setup/development/requirements.txt
    - name: Test with pytest
      run: |
        pytest --junitxml pytest.xml --cov-report term-missing --cov=api api/src | tee pytest-coverage.txt
    - name: Pytest coverage comment
      uses: MishaKav/pytest-coverage-comment@main
      with:
        pytest-coverage-path: ./pytest-coverage.txt
        junitxml-path: ./pytest.xml
        badge-title: pytest Coverage
